In [1]:
import pandas as pd  # Importar librería pandas
import datetime as dt 


In [159]:
# Cargar archivo parquet
producto = pd.read_parquet("producto.parquet")
producto


id        marca  \
0      0000000001663   LA ANÓNIMA   
1      0000000002288   LA ANÓNIMA   
2      0000000205870    SIN MARCA   
3      0000000205894    SIN MARCA   
4      0000000205955    SIN MARCA   
...              ...          ...   
72033  9569753142128  DELI-SITAS    
72034  9795403001143         MAYO   
72035  9990385651922         DANA   
72036  9990385651939         DANA   
72037  9990385651946         DANA   

                                                  nombre presentacion  \
0                        Radicheta Atada La Anonima 1 Un       1.0 un   
1                          Perejil Atado La Anonima 1 Un       1.0 un   
2                                       Ojo de Bife 1 Kg       1.0 kg   
3                      Milanesa de Peceto Novillito 1 Kg       1.0 kg   
4                             Chiquizuela Novillito 1 Kg       1.0 kg   
...                                                  ...          ...   
72033  Milhojas Cobertura de Chocolate Blanco Deli-Si...     500.0 gr   
72034                           Mini Pizzetas Mayo 12 Un      12.0 un   
72035                 Te Negro en Hebras Lata Dana 50 Gr      50.0 gr   
72036                 Te Verde en Hebras Lata Dana 50 Gr      50.0 gr   
72037            Yerba Mate Aromatizada Lata Dana 150 Gr     150.0 gr   

      categoria1 categoria2 categoria3  
0           None       None       None  
1           None       None       None  
2           None       None       None  
3           None       None       None  
4           None       None       None  
...          ...        ...        ...  
72033       None       None       None  
72034       None       None       None  
72035       None       None       None  
72036       None       None       None  
72037       None       None       None  

[72038 rows x 7 columns]

In [161]:
# Ver información del DataFrame. Por ejemplo: Las columnas de categorias solamente tienen 4 datos no nulos cada una de ellas.
producto.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72038 entries, 0 to 72037
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   id            72038 non-null  object
 1   marca         72036 non-null  object
 2   nombre        72036 non-null  object
 3   presentacion  72036 non-null  object
 4   categoria1    4 non-null      object
 5   categoria2    4 non-null      object
 6   categoria3    4 non-null      object
dtypes: object(7)
memory usage: 3.8+ MB


In [162]:
# Renombrar las columnas. Criterio utilizado: "PascalCase".

producto = producto.rename(columns={"id": "IdProducto", "marca": "Marca", "nombre": "Nombre",
                                    "presentacion": "Presentacion", "categoria1": "Categoria1", "categoria2": "Categoria2", "categoria3": "Categoria3"})
producto


IdProducto        Marca  \
0      0000000001663   LA ANÓNIMA   
1      0000000002288   LA ANÓNIMA   
2      0000000205870    SIN MARCA   
3      0000000205894    SIN MARCA   
4      0000000205955    SIN MARCA   
...              ...          ...   
72033  9569753142128  DELI-SITAS    
72034  9795403001143         MAYO   
72035  9990385651922         DANA   
72036  9990385651939         DANA   
72037  9990385651946         DANA   

                                                  Nombre Presentacion  \
0                        Radicheta Atada La Anonima 1 Un       1.0 un   
1                          Perejil Atado La Anonima 1 Un       1.0 un   
2                                       Ojo de Bife 1 Kg       1.0 kg   
3                      Milanesa de Peceto Novillito 1 Kg       1.0 kg   
4                             Chiquizuela Novillito 1 Kg       1.0 kg   
...                                                  ...          ...   
72033  Milhojas Cobertura de Chocolate Blanco Deli-Si...     500.0 gr   
72034                           Mini Pizzetas Mayo 12 Un      12.0 un   
72035                 Te Negro en Hebras Lata Dana 50 Gr      50.0 gr   
72036                 Te Verde en Hebras Lata Dana 50 Gr      50.0 gr   
72037            Yerba Mate Aromatizada Lata Dana 150 Gr     150.0 gr   

      Categoria1 Categoria2 Categoria3  
0           None       None       None  
1           None       None       None  
2           None       None       None  
3           None       None       None  
4           None       None       None  
...          ...        ...        ...  
72033       None       None       None  
72034       None       None       None  
72035       None       None       None  
72036       None       None       None  
72037       None       None       None  

[72038 rows x 7 columns]

In [163]:
# Consultar valores no nulos para saber si se pueden reemplazar. Al realizar este método se observa que no hay algún criterio
#  por el cual se pueda utilizar datos para reemplazar, ya que las categorías son distintas y carecen de datos como para poder unificar

producto.dropna(how="any")


IdProducto    Marca                                       Nombre  \
14903  7501001165260  PANTENE  Acondicionador Liso y Sedoso Pantene 400 Ml   
65297  7798183771123    GRIDO                Helado en Pote Tentacion 1 Lt   

      Presentacion                     Categoria1       Categoria2  \
14903     400.0 ml  Perfumería y Cuidado Personal  Cuidado Capilar   
65297       1.0 lt           Alimentos Congelados          Helados   

             Categoria3  
14903  Acondicionadores  
65297           Helados

In [164]:
# Para complementar al análisis anterior, se realiza una iteración para cada columna de categoría, que nos devuelva los indices(números de filas) de los datos
# no nulos.
def IndiceNoNulo(columna):
    for i, j in enumerate(columna):
        if j == None:
            continue
        else:
            print(i, j)


In [165]:
IndiceNoNulo(producto["Categoria1"])

14903 Perfumería y Cuidado Personal
53619 Almacén
55798 Almacén
65297 Alimentos Congelados


In [166]:
IndiceNoNulo(producto["Categoria2"])

14903 Cuidado Capilar
53619 Aceites
55798 Aceites
65297 Helados


In [167]:
IndiceNoNulo(producto["Categoria3"])

14903 Acondicionadores
53619 Aerosol
55798 Oliva
65297 Helados


In [168]:
def IndiceNulo(columna):
    for i, j in enumerate(columna):
        if j == None:
            print(i,j)
        else:
            continue

In [169]:
IndiceNulo(producto["Marca"])
IndiceNulo(producto["Nombre"])
IndiceNulo(producto["Presentacion"])

53619 None
55798 None
53619 None
55798 None
53619 None
55798 None


In [170]:
producto.iloc[53619]

IdProducto      7798024299045
Marca                    None
Nombre                   None
Presentacion             None
Categoria1            Almacén
Categoria2            Aceites
Categoria3            Aerosol
Name: 53619, dtype: object

In [171]:
producto.iloc[55798]

IdProducto      7798061190213
Marca                    None
Nombre                   None
Presentacion             None
Categoria1            Almacén
Categoria2            Aceites
Categoria3              Oliva
Name: 55798, dtype: object

In [172]:
producto.iloc[14903]

IdProducto                                    7501001165260
Marca                                               PANTENE
Nombre          Acondicionador Liso y Sedoso Pantene 400 Ml
Presentacion                                       400.0 ml
Categoria1                    Perfumería y Cuidado Personal
Categoria2                                  Cuidado Capilar
Categoria3                                 Acondicionadores
Name: 14903, dtype: object

In [173]:
producto.iloc[65297]

IdProducto                      7798183771123
Marca                                   GRIDO
Nombre          Helado en Pote Tentacion 1 Lt
Presentacion                           1.0 lt
Categoria1               Alimentos Congelados
Categoria2                            Helados
Categoria3                            Helados
Name: 65297, dtype: object

Como conclusion se observa que las únicas dos filas completas son 14903 y 65297.

Las filas 53619 y 55798 tienen datos nulos en Marca, Nombre y Presentación .
Y el resto de las filas tienen datos nulos en Categoria1, Categoria2 y Categoria3.


 Estos datos de falta de categorización en este momento carecen de significado porque, a mi criterio, no se le puede dar un valor significativo en nuestras tablas. Dado que no están completos ni se pueden obtener de otras tablas a través de uniones. No lo desestimaría ya que tal vez es un problema de carga en los datos o que recién se están actualizando y en un futuro si se le podría dar uso y asi cobrarán sentido. Por lo tanto en vez de eliminar las columnas, lo que se va a realizar va a ser un reemplazo en cada valor nulo por la descripción "SinCategoria", para dejar en claro que están sin categorizarse. Este es uno de los criterios que se podrían modificar una vez conversado con los demás integrantes responsables (o con acceso) a los datasets.

A su vez, con respectos a las filas donde los datos nulos son Marca, Nombre y Presentacion, también se reemplaza por SinDatos, ya que se saben las categorías y puede servir para conseguir los valores.

De esta manera, en ninguno de los datos de la tabla producto se perdería ningún Producto (ya que todos tienen IdProducto) y se podría rearmar tal vez la tabla completa.



In [174]:
# Reemplazar columnas de Categorias por "SinCategoria".
producto["Categoria1"].fillna("SinCategoria",inplace=True)
producto["Categoria2"].fillna("SinCategoria",inplace=True)
producto["Categoria3"].fillna("SinCategoria",inplace=True)


In [175]:
# Se reemplaza los valores nulos que quedan por "SinDatos".
producto.fillna("SinDatos",inplace=True)

In [176]:
# Se comprueba que las filas queden "completadas" con "SinDatos"
print(producto.iloc[53619],producto.iloc[55798])

IdProducto      7798024299045
Marca                SinDatos
Nombre               SinDatos
Presentacion         SinDatos
Categoria1            Almacén
Categoria2            Aceites
Categoria3            Aerosol
Name: 53619, dtype: object IdProducto      7798061190213
Marca                SinDatos
Nombre               SinDatos
Presentacion         SinDatos
Categoria1            Almacén
Categoria2            Aceites
Categoria3              Oliva
Name: 55798, dtype: object


In [177]:
# Ahora se observa que no queda ningún dato nulo en ninguna columna.
producto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72038 entries, 0 to 72037
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   IdProducto    72038 non-null  object
 1   Marca         72038 non-null  object
 2   Nombre        72038 non-null  object
 3   Presentacion  72038 non-null  object
 4   Categoria1    72038 non-null  object
 5   Categoria2    72038 non-null  object
 6   Categoria3    72038 non-null  object
dtypes: object(7)
memory usage: 3.8+ MB


In [178]:
producto.shape

(72038, 7)

In [179]:
# Se observa si hay duplicados y se eliminan (no hay).
producto.duplicated()
producto.drop_duplicates()


IdProducto        Marca  \
0      0000000001663   LA ANÓNIMA   
1      0000000002288   LA ANÓNIMA   
2      0000000205870    SIN MARCA   
3      0000000205894    SIN MARCA   
4      0000000205955    SIN MARCA   
...              ...          ...   
72033  9569753142128  DELI-SITAS    
72034  9795403001143         MAYO   
72035  9990385651922         DANA   
72036  9990385651939         DANA   
72037  9990385651946         DANA   

                                                  Nombre Presentacion  \
0                        Radicheta Atada La Anonima 1 Un       1.0 un   
1                          Perejil Atado La Anonima 1 Un       1.0 un   
2                                       Ojo de Bife 1 Kg       1.0 kg   
3                      Milanesa de Peceto Novillito 1 Kg       1.0 kg   
4                             Chiquizuela Novillito 1 Kg       1.0 kg   
...                                                  ...          ...   
72033  Milhojas Cobertura de Chocolate Blanco Deli-Si...     500.0 gr   
72034                           Mini Pizzetas Mayo 12 Un      12.0 un   
72035                 Te Negro en Hebras Lata Dana 50 Gr      50.0 gr   
72036                 Te Verde en Hebras Lata Dana 50 Gr      50.0 gr   
72037            Yerba Mate Aromatizada Lata Dana 150 Gr     150.0 gr   

         Categoria1    Categoria2    Categoria3  
0      SinCategoria  SinCategoria  SinCategoria  
1      SinCategoria  SinCategoria  SinCategoria  
2      SinCategoria  SinCategoria  SinCategoria  
3      SinCategoria  SinCategoria  SinCategoria  
4      SinCategoria  SinCategoria  SinCategoria  
...             ...           ...           ...  
72033  SinCategoria  SinCategoria  SinCategoria  
72034  SinCategoria  SinCategoria  SinCategoria  
72035  SinCategoria  SinCategoria  SinCategoria  
72036  SinCategoria  SinCategoria  SinCategoria  
72037  SinCategoria  SinCategoria  SinCategoria  

[72038 rows x 7 columns]

In [180]:
# Unificar en la columna "Marca" las primeras letras en mayúsculas de cada palabra.
producto["Marca"]=producto["Marca"].str.title()
producto

IdProducto        Marca  \
0      0000000001663   La Anónima   
1      0000000002288   La Anónima   
2      0000000205870    Sin Marca   
3      0000000205894    Sin Marca   
4      0000000205955    Sin Marca   
...              ...          ...   
72033  9569753142128  Deli-Sitas    
72034  9795403001143         Mayo   
72035  9990385651922         Dana   
72036  9990385651939         Dana   
72037  9990385651946         Dana   

                                                  Nombre Presentacion  \
0                        Radicheta Atada La Anonima 1 Un       1.0 un   
1                          Perejil Atado La Anonima 1 Un       1.0 un   
2                                       Ojo de Bife 1 Kg       1.0 kg   
3                      Milanesa de Peceto Novillito 1 Kg       1.0 kg   
4                             Chiquizuela Novillito 1 Kg       1.0 kg   
...                                                  ...          ...   
72033  Milhojas Cobertura de Chocolate Blanco Deli-Si...     500.0 gr   
72034                           Mini Pizzetas Mayo 12 Un      12.0 un   
72035                 Te Negro en Hebras Lata Dana 50 Gr      50.0 gr   
72036                 Te Verde en Hebras Lata Dana 50 Gr      50.0 gr   
72037            Yerba Mate Aromatizada Lata Dana 150 Gr     150.0 gr   

         Categoria1    Categoria2    Categoria3  
0      SinCategoria  SinCategoria  SinCategoria  
1      SinCategoria  SinCategoria  SinCategoria  
2      SinCategoria  SinCategoria  SinCategoria  
3      SinCategoria  SinCategoria  SinCategoria  
4      SinCategoria  SinCategoria  SinCategoria  
...             ...           ...           ...  
72033  SinCategoria  SinCategoria  SinCategoria  
72034  SinCategoria  SinCategoria  SinCategoria  
72035  SinCategoria  SinCategoria  SinCategoria  
72036  SinCategoria  SinCategoria  SinCategoria  
72037  SinCategoria  SinCategoria  SinCategoria  

[72038 rows x 7 columns]

In [181]:
# Quitar los valores de numeros y unidades/gramos/kilos/milimetros/centimetros cubicos/Litros de la misma columna que el nombre 
# ya que están en la columna de presentación también. Excepto los que hacen alusión a su descripción. Tambien a las promociones
# por ejemplo "Aperitivo Gancia 950 Cc + Aperitivo Gancia Martini Rosso 995 Cc Pa" ó "Estuche Fernet Branca 75 Cc + 2 Vasos".

producto["Nombre"]= producto["Nombre"].astype(str).apply(lambda x:x.strip(" .0123456789UnKgGrmlcLtkx"))


In [182]:
# Se reemplaza la descripción de Marca "Sin Marca" por "SinDatos" para unificar criterios y emprolijar.
producto["Marca"].replace("Sin Marca","SinDatos",inplace=True)

In [183]:
# Se reasignan orden de las columnas para mayor prolijidad.
producto=producto.reindex(columns=["IdProducto","Nombre","Marca","Presentacion","Categoria1","Categoria2","Categoria3"])

In [184]:
producto

IdProducto                                             Nombre  \
0      0000000001663                         Radicheta Atada La Anonima   
1      0000000002288                           Perejil Atado La Anonima   
2      0000000205870                                        Ojo de Bife   
3      0000000205894                       Milanesa de Peceto Novillito   
4      0000000205955                              Chiquizuela Novillito   
...              ...                                                ...   
72033  9569753142128  Milhojas Cobertura de Chocolate Blanco Deli-Sitas   
72034  9795403001143                                 Mini Pizzetas Mayo   
72035  9990385651922                       Te Negro en Hebras Lata Dana   
72036  9990385651939                       Te Verde en Hebras Lata Dana   
72037  9990385651946                   Yerba Mate Aromatizada Lata Dana   

             Marca Presentacion    Categoria1    Categoria2    Categoria3  
0       La Anónima       1.0 un  SinCategoria  SinCategoria  SinCategoria  
1       La Anónima       1.0 un  SinCategoria  SinCategoria  SinCategoria  
2         SinDatos       1.0 kg  SinCategoria  SinCategoria  SinCategoria  
3         SinDatos       1.0 kg  SinCategoria  SinCategoria  SinCategoria  
4         SinDatos       1.0 kg  SinCategoria  SinCategoria  SinCategoria  
...            ...          ...           ...           ...           ...  
72033  Deli-Sitas      500.0 gr  SinCategoria  SinCategoria  SinCategoria  
72034         Mayo      12.0 un  SinCategoria  SinCategoria  SinCategoria  
72035         Dana      50.0 gr  SinCategoria  SinCategoria  SinCategoria  
72036         Dana      50.0 gr  SinCategoria  SinCategoria  SinCategoria  
72037         Dana     150.0 gr  SinCategoria  SinCategoria  SinCategoria  

[72038 rows x 7 columns]

In [186]:
producto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72038 entries, 0 to 72037
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   IdProducto    72038 non-null  object
 1   Nombre        72038 non-null  object
 2   Marca         72038 non-null  object
 3   Presentacion  72038 non-null  object
 4   Categoria1    72038 non-null  object
 5   Categoria2    72038 non-null  object
 6   Categoria3    72038 non-null  object
dtypes: object(7)
memory usage: 3.8+ MB


In [187]:
# Exportar a carpeta local.
producto.to_csv("Producto.csv", index=False)


In [188]:
# Exportar a carpeta de MySQL.
producto.to_csv(r"C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\Producto.csv",index=False)

In [61]:
# Cargar archivo json
semana0305 = pd.read_json("precios_semana_20200503.json")
semana0305


precio    producto_id sucursal_id
0         29.9  0000000002288     2-1-187
1         39.9  0000000002288     2-3-247
2       499.99  0000000205870     9-1-685
3       539.99  0000000205870      9-2-22
4       519.99  0000000205870      9-2-59
...        ...            ...         ...
397729  139.99  9569753142128      25-1-1
397730   34.99  9795403001143      25-1-1
397731   312.5  9990385651922       5-1-5
397732   312.5  9990385651939       5-1-5
397733   198.9  9990385651946       5-1-5

[397734 rows x 3 columns]

In [62]:
# Ver información del DataFrame. No tiene nulos.
semana0305.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397734 entries, 0 to 397733
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype 
---  ------       --------------   ----- 
 0   precio       397734 non-null  object
 1   producto_id  397734 non-null  object
 2   sucursal_id  397734 non-null  object
dtypes: object(3)
memory usage: 9.1+ MB


In [63]:
# Renombrar las columnas. Criterio utilizado: "PascalCase".
semana0305 = semana0305.rename(columns={
                               "precio": "Precio", "producto_id": "IdProducto", "sucursal_id": "IdSucursal"})
semana0305


Precio     IdProducto IdSucursal
0         29.9  0000000002288    2-1-187
1         39.9  0000000002288    2-3-247
2       499.99  0000000205870    9-1-685
3       539.99  0000000205870     9-2-22
4       519.99  0000000205870     9-2-59
...        ...            ...        ...
397729  139.99  9569753142128     25-1-1
397730   34.99  9795403001143     25-1-1
397731   312.5  9990385651922      5-1-5
397732   312.5  9990385651939      5-1-5
397733   198.9  9990385651946      5-1-5

[397734 rows x 3 columns]

In [64]:
# Se realiza una función lambda que quite los "-" al IdSucursal ya que dificulta la esteticidad 
# para las posteriores consultas tambien en las bases de datos.

semana0305['IdSucursal']=semana0305['IdSucursal'].apply(lambda x: x.replace('-',''))

In [65]:
# Para saber cuantos digitos máximos tiene el IdSucursal.
semana0305["IdSucursal"].max()

'935961'

In [66]:
# Agregarle "0" a la izquierda para que quede una cantidad fija de caracteres en toda la columna.
semana0305["IdSucursal"]= semana0305["IdSucursal"].str.zfill(8)

In [67]:
semana0305

Precio     IdProducto IdSucursal
0         29.9  0000000002288   00021187
1         39.9  0000000002288   00023247
2       499.99  0000000205870   00091685
3       539.99  0000000205870   00009222
4       519.99  0000000205870   00009259
...        ...            ...        ...
397729  139.99  9569753142128   00002511
397730   34.99  9795403001143   00002511
397731   312.5  9990385651922   00000515
397732   312.5  9990385651939   00000515
397733   198.9  9990385651946   00000515

[397734 rows x 3 columns]

In [68]:
# Modificar el orden de las columnas, para normalizar todas las tablas.
semana0305=semana0305.reindex(columns=["IdProducto","IdSucursal","Precio"])

In [69]:
semana0305.drop_duplicates()

IdProducto IdSucursal  Precio
0       0000000002288   00021187    29.9
1       0000000002288   00023247    39.9
2       0000000205870   00091685  499.99
3       0000000205870   00009222  539.99
4       0000000205870   00009259  519.99
...               ...        ...     ...
397729  9569753142128   00002511  139.99
397730  9795403001143   00002511   34.99
397731  9990385651922   00000515   312.5
397732  9990385651939   00000515   312.5
397733  9990385651946   00000515   198.9

[397734 rows x 3 columns]

In [70]:
semana0305.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397734 entries, 0 to 397733
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype 
---  ------      --------------   ----- 
 0   IdProducto  397734 non-null  object
 1   IdSucursal  397734 non-null  object
 2   Precio      397734 non-null  object
dtypes: object(3)
memory usage: 9.1+ MB


In [71]:
# Se observa que el tipo de dato de Precio es object, por lo tanto lo cambiaremos a float para tener dos decimales luego de la coma. 
semana0305["Precio"]=pd.to_numeric(semana0305["Precio"],errors="coerce")
#semana0305["Precio"] = semana0305["Precio"].astype(float, errors = 'raise')

In [72]:
semana0305.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397734 entries, 0 to 397733
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   IdProducto  397734 non-null  object 
 1   IdSucursal  397734 non-null  object 
 2   Precio      395610 non-null  float64
dtypes: float64(1), object(2)
memory usage: 9.1+ MB


In [73]:
semana0305

IdProducto IdSucursal  Precio
0       0000000002288   00021187   29.90
1       0000000002288   00023247   39.90
2       0000000205870   00091685  499.99
3       0000000205870   00009222  539.99
4       0000000205870   00009259  519.99
...               ...        ...     ...
397729  9569753142128   00002511  139.99
397730  9795403001143   00002511   34.99
397731  9990385651922   00000515  312.50
397732  9990385651939   00000515  312.50
397733  9990385651946   00000515  198.90

[397734 rows x 3 columns]

In [74]:
# Reemplazar los nulos de "Precio" por "0". Como criterio al menos en este caso no lo eliminaría por que son pocos y 
# es tal vez un dato recuperable. Luego se consultaría con Data Analyst o ejecutivos sobre la decisión a tomar al respecto. 
# Ya que no es objeto de estudio en este caso. Como posible sugerencia para consultar en el caso de que no existan datos y 
# no se puedan recuperar, un criterio podría ser el promedio de las distintas sucursarles.

semana0305["Precio"]=semana0305["Precio"].fillna(0)

In [75]:
semana0305.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397734 entries, 0 to 397733
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   IdProducto  397734 non-null  object 
 1   IdSucursal  397734 non-null  object 
 2   Precio      397734 non-null  float64
dtypes: float64(1), object(2)
memory usage: 9.1+ MB


In [76]:
# Ver si exportar sin indice o si puede llegar a ser util para algo el dia de mañana.
semana0305.to_csv("Semana0305.csv",index=False)


In [240]:
# Cargar archivo xlsx, cada hoja por separado .
semana1904a = pd.read_excel(
             "precios_semanas_20200419_20200426.xlsx", sheet_name="precios_20200426_20200426")
semana1904a


precio sucursal_id   producto_id
0         399.0     2-1-092  2.288000e+03
1         299.0     2-1-206  2.288000e+03
2         399.0     2-2-241  2.288000e+03
3       49999.0     9-1-430  2.058700e+05
4       53999.0       9-2-4  2.058700e+05
...         ...         ...           ...
478904  13999.0      25-1-1  9.569753e+12
478905   3499.0      25-1-1  9.795403e+12
478906   3125.0       5-1-3  9.990386e+12
478907   3125.0       5-1-3  9.990386e+12
478908   1989.0       5-1-3  9.990386e+12

[478909 rows x 3 columns]

In [241]:
semana1904a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478909 entries, 0 to 478908
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   precio       477173 non-null  float64
 1   sucursal_id  478909 non-null  object 
 2   producto_id  465390 non-null  float64
dtypes: float64(2), object(1)
memory usage: 11.0+ MB


In [242]:
# Renombrar las columnas. Criterio utilizado: "PascalCase".
semana1904a = semana1904a.rename(columns={
                               "precio": "Precio", "sucursal_id": "IdSucursal", "producto_id": "IdProducto"})
semana1904a


Precio IdSucursal    IdProducto
0         399.0    2-1-092  2.288000e+03
1         299.0    2-1-206  2.288000e+03
2         399.0    2-2-241  2.288000e+03
3       49999.0    9-1-430  2.058700e+05
4       53999.0      9-2-4  2.058700e+05
...         ...        ...           ...
478904  13999.0     25-1-1  9.569753e+12
478905   3499.0     25-1-1  9.795403e+12
478906   3125.0      5-1-3  9.990386e+12
478907   3125.0      5-1-3  9.990386e+12
478908   1989.0      5-1-3  9.990386e+12

[478909 rows x 3 columns]

In [243]:
# Se realiza una función lambda que quite los "-" al IdSucursal ya que dificulta la esteticidad 
# para las posteriores consultas tambien en las bases de datos.

semana1904a['IdSucursal']=semana1904a['IdSucursal'].apply(lambda x: x.replace('-',''))

In [244]:
# Se le agregan a la columna IdProducto los ceros a la izquierda que faltan para completar los 8 caracteres.
semana1904a["IdSucursal"]=semana1904a["IdSucursal"].str.zfill(8)

In [245]:
semana1904a

Precio IdSucursal    IdProducto
0         399.0   00021092  2.288000e+03
1         299.0   00021206  2.288000e+03
2         399.0   00022241  2.288000e+03
3       49999.0   00091430  2.058700e+05
4       53999.0   00000924  2.058700e+05
...         ...        ...           ...
478904  13999.0   00002511  9.569753e+12
478905   3499.0   00002511  9.795403e+12
478906   3125.0   00000513  9.990386e+12
478907   3125.0   00000513  9.990386e+12
478908   1989.0   00000513  9.990386e+12

[478909 rows x 3 columns]

In [246]:
# Se pasan los datos de la columna IdProducto de float a string.
semana1904a["IdProducto"] =semana1904a['IdProducto'].astype(str, errors = 'raise')

In [247]:
# Se quitan los ultimos caracteres de la cadena, ya que no son correctos. Porque sobran y porque el IdProducto son 13 caracteres
semana1904a["IdProducto"] = semana1904a["IdProducto"].astype(str).apply(lambda x:x.strip(" .0"))

In [248]:
# Se le agregan a la columna IdProducto los ceros a la izquierda que faltan para completar los 13 caracteres.
semana1904a["IdProducto"]=semana1904a["IdProducto"].str.zfill(13)

In [249]:
semana1904a

Precio IdSucursal     IdProducto
0         399.0   00021092  0000000002288
1         299.0   00021206  0000000002288
2         399.0   00022241  0000000002288
3       49999.0   00091430  0000000020587
4       53999.0   00000924  0000000020587
...         ...        ...            ...
478904  13999.0   00002511  9569753142128
478905   3499.0   00002511  9795403001143
478906   3125.0   00000513  9990385651922
478907   3125.0   00000513  9990385651939
478908   1989.0   00000513  9990385651946

[478909 rows x 3 columns]

In [252]:
semana1904a.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478909 entries, 0 to 478908
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   Precio      478909 non-null  float64
 1   IdSucursal  478909 non-null  object 
 2   IdProducto  478909 non-null  object 
dtypes: float64(1), object(2)
memory usage: 11.0+ MB


In [251]:
# Reemplazar los nulos de "Precio" por "0". Como criterio al menos en este caso no lo eliminaría por que son pocos y 
# es tal vez un dato recuperable. Luego se consultaría con Data Analyst o ejecutivos sobre la decisión a tomar al respecto. 
# Ya que no es objeto de estudio en este caso. Como posible sugerencia para consultar en el caso de que no existan datos y 
# no se puedan recuperar, un criterio podría ser el promedio de las distintas sucursarles.

semana1904a["Precio"]=semana1904a["Precio"].fillna(0)

In [217]:
# Cargar archivo xlsx, cada hoja por separado .
semana1904b = pd.read_excel(
             "precios_semanas_20200419_20200426.xlsx", sheet_name="precios_20200419_20200419")
semana1904b


precio          sucursal_id      producto_id
0        29.90              2-1-184           2288.0
1        39.90              2-1-206           2288.0
2       499.99              9-1-430         205870.0
3       539.99              9-2-107         205870.0
4       539.99  5218-03-09 00:00:00         205870.0
...        ...                  ...              ...
458538  139.99  2001-01-25 00:00:00  9569753142128.0
458539   34.99  2001-01-25 00:00:00  9795403001143.0
458540  312.50  2003-01-05 00:00:00  9990385651922.0
458541  312.50  2003-01-05 00:00:00  9990385651939.0
458542  198.90  2003-01-05 00:00:00  9990385651946.0

[458543 rows x 3 columns]

In [218]:
semana1904b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458543 entries, 0 to 458542
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   precio       456736 non-null  float64
 1   sucursal_id  458543 non-null  object 
 2   producto_id  458543 non-null  object 
dtypes: float64(1), object(2)
memory usage: 10.5+ MB


In [219]:
# Renombrar las columnas. Criterio utilizado: "PascalCase".
semana1904b = semana1904b.rename(columns={
                               "precio": "Precio", "sucursal_id": "IdSucursal", "producto_id": "IdProducto"})
semana1904b


Precio           IdSucursal       IdProducto
0        29.90              2-1-184           2288.0
1        39.90              2-1-206           2288.0
2       499.99              9-1-430         205870.0
3       539.99              9-2-107         205870.0
4       539.99  5218-03-09 00:00:00         205870.0
...        ...                  ...              ...
458538  139.99  2001-01-25 00:00:00  9569753142128.0
458539   34.99  2001-01-25 00:00:00  9795403001143.0
458540  312.50  2003-01-05 00:00:00  9990385651922.0
458541  312.50  2003-01-05 00:00:00  9990385651939.0
458542  198.90  2003-01-05 00:00:00  9990385651946.0

[458543 rows x 3 columns]

In [220]:
semana1904b["IdSucursal"]=semana1904b["IdSucursal"].astype(str)

In [224]:
def normalizacion(x):
    if " " in x:
        x=x.split(" ")[0]
        a=x.split("-")[0]
        b=x.split("-")[1]
        c=x.split("-")[2]
        x=c +"-" +b + "-" +a
    return x  

In [225]:
normalizacion(semana1904b["IdSucursal"])

0                     2-1-184
1                     2-1-206
2                     9-1-430
3                     9-2-107
4         5218-03-09 00:00:00
                 ...         
458538    2001-01-25 00:00:00
458539    2001-01-25 00:00:00
458540    2003-01-05 00:00:00
458541    2003-01-05 00:00:00
458542    2003-01-05 00:00:00
Name: IdSucursal, Length: 458543, dtype: object

In [226]:
semana1904b["IdSucursal"]=semana1904b["IdSucursal"].apply(normalizacion) 

In [227]:
semana1904b

Precio  IdSucursal       IdProducto
0        29.90     2-1-184           2288.0
1        39.90     2-1-206           2288.0
2       499.99     9-1-430         205870.0
3       539.99     9-2-107         205870.0
4       539.99  09-03-5218         205870.0
...        ...         ...              ...
458538  139.99  25-01-2001  9569753142128.0
458539   34.99  25-01-2001  9795403001143.0
458540  312.50  05-01-2003  9990385651922.0
458541  312.50  05-01-2003  9990385651939.0
458542  198.90  05-01-2003  9990385651946.0

[458543 rows x 3 columns]

In [93]:
"""def IdSucursal(cadena):
    if type(cadena)==str:
        return cadena
    elif type(cadena)==dt.datetime:
        cadenasuc=cadena.strftime("%d/%m/%Y")
        cadenanueva=cadenasuc.replace("/","-")
        lista=cadenanueva
        for i in range(0,2):
            listanueva=lista.replace("0","")
        return listanueva"""

In [94]:
#IdSucursal(semana1904b["IdSucursal"])

In [95]:
#semana1904b["IdSucursal"]=semana1904b["IdSucursal"].apply(IdSucursal)

In [228]:
# Se realiza una función lambda que quite los "-" al IdSucursal ya que dificulta la esteticidad 
# para las posteriores consultas tambien en las bases de datos.

semana1904b['IdSucursal']=semana1904b['IdSucursal'].apply(lambda x: x.replace('-',''))

In [229]:
semana1904b

Precio IdSucursal       IdProducto
0        29.90      21184           2288.0
1        39.90      21206           2288.0
2       499.99      91430         205870.0
3       539.99      92107         205870.0
4       539.99   09035218         205870.0
...        ...        ...              ...
458538  139.99   25012001  9569753142128.0
458539   34.99   25012001  9795403001143.0
458540  312.50   05012003  9990385651922.0
458541  312.50   05012003  9990385651939.0
458542  198.90   05012003  9990385651946.0

[458543 rows x 3 columns]

In [230]:
# Se le agregan a la columna IdProducto los ceros a la izquierda que faltan para completar los 8 caracteres.
semana1904b["IdSucursal"]=semana1904b["IdSucursal"].str.zfill(8)

In [231]:
semana1904b

Precio IdSucursal       IdProducto
0        29.90   00021184           2288.0
1        39.90   00021206           2288.0
2       499.99   00091430         205870.0
3       539.99   00092107         205870.0
4       539.99   09035218         205870.0
...        ...        ...              ...
458538  139.99   25012001  9569753142128.0
458539   34.99   25012001  9795403001143.0
458540  312.50   05012003  9990385651922.0
458541  312.50   05012003  9990385651939.0
458542  198.90   05012003  9990385651946.0

[458543 rows x 3 columns]

In [232]:
# Se quitan los ultimos caracteres de la cadena, ya que no son correctos. Porque sobran y porque el IdProducto son 13 caracteres
semana1904b["IdProducto"] = semana1904b["IdProducto"].astype(str).apply(lambda x:x.strip(" .0"))

In [233]:
# Se le agregan a la columna IdProducto los ceros a la izquierda que faltan para completar los 13 caracteres.
semana1904b["IdProducto"]=semana1904b["IdProducto"].str.zfill(13)

In [234]:
semana1904b

Precio IdSucursal     IdProducto
0        29.90   00021184  0000000002288
1        39.90   00021206  0000000002288
2       499.99   00091430  0000000020587
3       539.99   00092107  0000000020587
4       539.99   09035218  0000000020587
...        ...        ...            ...
458538  139.99   25012001  9569753142128
458539   34.99   25012001  9795403001143
458540  312.50   05012003  9990385651922
458541  312.50   05012003  9990385651939
458542  198.90   05012003  9990385651946

[458543 rows x 3 columns]

In [235]:
semana1904b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458543 entries, 0 to 458542
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   Precio      456736 non-null  float64
 1   IdSucursal  458543 non-null  object 
 2   IdProducto  458543 non-null  object 
dtypes: float64(1), object(2)
memory usage: 10.5+ MB


In [236]:
# Reemplazar los nulos de "Precio" por "0". Como criterio al menos en este caso no lo eliminaría por que son pocos y 
# es tal vez un dato recuperable. Luego se consultaría con Data Analyst o ejecutivos sobre la decisión a tomar al respecto. 
# Ya que no es objeto de estudio en este caso. Como posible sugerencia para consultar en el caso de que no existan datos y 
# no se puedan recuperar, un criterio podría ser el promedio de las distintas sucursarles.

semana1904b["Precio"]=semana1904b["Precio"].fillna(0)

In [237]:
semana1904b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458543 entries, 0 to 458542
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   Precio      458543 non-null  float64
 1   IdSucursal  458543 non-null  object 
 2   IdProducto  458543 non-null  object 
dtypes: float64(1), object(2)
memory usage: 10.5+ MB


In [238]:
semana1904b

Precio IdSucursal     IdProducto
0        29.90   00021184  0000000002288
1        39.90   00021206  0000000002288
2       499.99   00091430  0000000020587
3       539.99   00092107  0000000020587
4       539.99   09035218  0000000020587
...        ...        ...            ...
458538  139.99   25012001  9569753142128
458539   34.99   25012001  9795403001143
458540  312.50   05012003  9990385651922
458541  312.50   05012003  9990385651939
458542  198.90   05012003  9990385651946

[458543 rows x 3 columns]

In [253]:
# Concatenar (juntar) ambas pestañas en un solo dataframe. Esto se podría hacer también en SQL con "union"
semana1904 = pd.concat([semana1904b,semana1904a], axis=0, ignore_index=True)
semana1904


Precio IdSucursal     IdProducto
0          29.90   00021184  0000000002288
1          39.90   00021206  0000000002288
2         499.99   00091430  0000000020587
3         539.99   00092107  0000000020587
4         539.99   09035218  0000000020587
...          ...        ...            ...
937447  13999.00   00002511  9569753142128
937448   3499.00   00002511  9795403001143
937449   3125.00   00000513  9990385651922
937450   3125.00   00000513  9990385651939
937451   1989.00   00000513  9990385651946

[937452 rows x 3 columns]

In [254]:
semana1904=semana1904.reindex(columns=["IdProducto","IdSucursal","Precio"])

In [255]:
semana1904

IdProducto IdSucursal    Precio
0       0000000002288   00021184     29.90
1       0000000002288   00021206     39.90
2       0000000020587   00091430    499.99
3       0000000020587   00092107    539.99
4       0000000020587   09035218    539.99
...               ...        ...       ...
937447  9569753142128   00002511  13999.00
937448  9795403001143   00002511   3499.00
937449  9990385651922   00000513   3125.00
937450  9990385651939   00000513   3125.00
937451  9990385651946   00000513   1989.00

[937452 rows x 3 columns]

In [256]:
semana1904.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 937452 entries, 0 to 937451
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   IdProducto  937452 non-null  object 
 1   IdSucursal  937452 non-null  object 
 2   Precio      937452 non-null  float64
dtypes: float64(1), object(2)
memory usage: 21.5+ MB


In [257]:
# Ver si exportar sin indice o si puede llegar a ser util para algo el dia de mañana.
semana1904.to_csv("Semana1904.csv", index=False)


In [41]:
# Cargar archivo txt. No tiene separación (Cada fila en una sola columna)

semana1805 = pd.read_csv("precios_semana_20200518.txt")
semana1805


precio|producto_id|sucursal_id
0          29.9|0000000002288|2-1-009
1          32.9|0000000002288|2-1-037
2          36.9|0000000002288|2-1-090
3          39.9|0000000002288|2-3-247
4        499.99|0000000205870|9-1-430
...                               ...
415288    149.99|9569753142128|25-1-1
415289     34.99|9795403001143|25-1-1
415290      312.5|9990385651922|5-1-4
415291      312.5|9990385651939|5-1-4
415292      198.9|9990385651946|5-1-4

[415293 rows x 1 columns]

In [42]:
# Ver información del DataFrame. Está todo en una sola columna.
semana1805.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415293 entries, 0 to 415292
Data columns (total 1 columns):
 #   Column                          Non-Null Count   Dtype 
---  ------                          --------------   ----- 
 0   precio|producto_id|sucursal_id  415293 non-null  object
dtypes: object(1)
memory usage: 3.2+ MB


In [43]:
# Separar las columnas por el tabulador y luego modificar el nombre de las columnas.

semana1805 = semana1805["precio|producto_id|sucursal_id"].str.split(
    "|", expand=True)
# Modificar nombre columnas.   
semana1805 = semana1805.rename(
    columns={0: "Precio", 1: "IdProducto", 2: "IdSucursal"})
semana1805




Precio     IdProducto IdSucursal
0         29.9  0000000002288    2-1-009
1         32.9  0000000002288    2-1-037
2         36.9  0000000002288    2-1-090
3         39.9  0000000002288    2-3-247
4       499.99  0000000205870    9-1-430
...        ...            ...        ...
415288  149.99  9569753142128     25-1-1
415289   34.99  9795403001143     25-1-1
415290   312.5  9990385651922      5-1-4
415291   312.5  9990385651939      5-1-4
415292   198.9  9990385651946      5-1-4

[415293 rows x 3 columns]

In [44]:
#Chequear el valor máximo de caracteres en la columna
semana1805["IdSucursal"].max() 

'9-3-5277'

In [45]:
# Se realiza una función lambda que quite los "-" al IdSucursal ya que dificulta la esteticidad 
# para las posteriores consultas tambien en las bases de datos.

semana1805['IdSucursal']=semana1805['IdSucursal'].apply(lambda x: x.replace('-',''))

In [46]:
semana1805

Precio     IdProducto IdSucursal
0         29.9  0000000002288      21009
1         32.9  0000000002288      21037
2         36.9  0000000002288      21090
3         39.9  0000000002288      23247
4       499.99  0000000205870      91430
...        ...            ...        ...
415288  149.99  9569753142128       2511
415289   34.99  9795403001143       2511
415290   312.5  9990385651922        514
415291   312.5  9990385651939        514
415292   198.9  9990385651946        514

[415293 rows x 3 columns]

In [47]:
# Ver información del DataFrame. No tiene nulos.
semana1805.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415293 entries, 0 to 415292
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype 
---  ------      --------------   ----- 
 0   Precio      415293 non-null  object
 1   IdProducto  415293 non-null  object
 2   IdSucursal  415293 non-null  object
dtypes: object(3)
memory usage: 9.5+ MB


In [48]:
# Reemplazar los nulos de IdSucursal por "0". Como criterio al menos en este caso no lo eliminaría por que son pocos y 
# es tal vez un dato recuperable y a su vez la columna de IdSucursal es importante. Luego se consultaría con Data Analyst 
# o ejecutivos sobre la decisión a tomar al respecto. Ya que no es objeto de estudio en este caso.

semana1805["IdSucursal"]=semana1805["IdSucursal"].fillna(0)

In [49]:
# Completar con ceros el campo IdSucursal para llegar a 8 caracteres.
semana1805["IdSucursal"]=semana1805["IdSucursal"].str.zfill(8)

In [50]:
semana1805.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415293 entries, 0 to 415292
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype 
---  ------      --------------   ----- 
 0   Precio      415293 non-null  object
 1   IdProducto  415293 non-null  object
 2   IdSucursal  415293 non-null  object
dtypes: object(3)
memory usage: 9.5+ MB


In [51]:
semana1805

Precio     IdProducto IdSucursal
0         29.9  0000000002288   00021009
1         32.9  0000000002288   00021037
2         36.9  0000000002288   00021090
3         39.9  0000000002288   00023247
4       499.99  0000000205870   00091430
...        ...            ...        ...
415288  149.99  9569753142128   00002511
415289   34.99  9795403001143   00002511
415290   312.5  9990385651922   00000514
415291   312.5  9990385651939   00000514
415292   198.9  9990385651946   00000514

[415293 rows x 3 columns]

In [52]:
semana1805.describe()

Precio     IdProducto IdSucursal
count   415293         415293     415293
unique   22043          60745        142
top      119.0  7791293022567   00004912
freq      2257            101      15128

In [53]:
semana1805["Precio"].describe()

count     415293
unique     22043
top        119.0
freq        2257
Name: Precio, dtype: object

In [54]:
semana1805=semana1805.reindex(columns=["IdProducto","IdSucursal","Precio"])

In [56]:
# Se observa que el tipo de dato de Precio es object, por lo tanto lo cambiaremos a float para tener dos decimales luego de la coma. 
semana1805["Precio"]=pd.to_numeric(semana1805["Precio"],errors="coerce")
#semana1805["Precio"] = semana1805["Precio"].astype(float, errors = 'raise')

In [57]:
semana1805.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415293 entries, 0 to 415292
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   IdProducto  415293 non-null  object 
 1   IdSucursal  415293 non-null  object 
 2   Precio      413333 non-null  float64
dtypes: float64(1), object(2)
memory usage: 9.5+ MB


In [58]:
# Reemplazar los nulos de "Precio" por "0". Como criterio al menos en este caso no lo eliminaría por que son pocos y 
# es tal vez un dato recuperable. Luego se consultaría con Data Analyst o ejecutivos sobre la decisión a tomar al respecto. 
# Ya que no es objeto de estudio en este caso. Como posible sugerencia para consultar en el caso de que no existan datos y 
# no se puedan recuperar, un criterio podría ser el promedio de las distintas sucursarles.

semana1805["Precio"]=semana1805["Precio"].fillna(0)

In [59]:
semana1805.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415293 entries, 0 to 415292
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   IdProducto  415293 non-null  object 
 1   IdSucursal  415293 non-null  object 
 2   Precio      415293 non-null  float64
dtypes: float64(1), object(2)
memory usage: 9.5+ MB


In [60]:
# Ver si exportar sin indice o si puede llegar a ser util para algo el dia de mañana.
semana1805.to_csv("Semana1805.csv",index=False)


In [77]:
# Cargar archivo csv.
semana1304 = pd.read_csv("precios_semana_20200413.csv", encoding="utf-16")
semana1304


precio    producto_id sucursal_id
0        29.90  0000000001663     2-1-014
1        29.90  0000000002288     2-1-032
2        39.90  0000000002288     2-1-096
3       499.99  0000000205870     9-1-686
4       519.99  0000000205870     9-2-248
...        ...            ...         ...
472161  139.99  9569753142128      25-1-1
472162   34.99  9795403001143      25-1-1
472163  312.50  9990385651922       5-1-3
472164  312.50  9990385651939       5-1-3
472165  198.90  9990385651946       5-1-3

[472166 rows x 3 columns]

In [79]:
# Ver información del DataFrame. Todas las columnas tienen datos nulos.
semana1304.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472166 entries, 0 to 472165
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   precio       472153 non-null  float64
 1   producto_id  472151 non-null  object 
 2   sucursal_id  472151 non-null  object 
dtypes: float64(1), object(2)
memory usage: 10.8+ MB


In [80]:
# Renombrar las columnas. Criterio utilizado: "PascalCase".
semana1304 = semana1304.rename(columns={
                               "precio": "Precio", "producto_id": "IdProducto", "sucursal_id": "IdSucursal"})
semana1304


Precio     IdProducto IdSucursal
0        29.90  0000000001663    2-1-014
1        29.90  0000000002288    2-1-032
2        39.90  0000000002288    2-1-096
3       499.99  0000000205870    9-1-686
4       519.99  0000000205870    9-2-248
...        ...            ...        ...
472161  139.99  9569753142128     25-1-1
472162   34.99  9795403001143     25-1-1
472163  312.50  9990385651922      5-1-3
472164  312.50  9990385651939      5-1-3
472165  198.90  9990385651946      5-1-3

[472166 rows x 3 columns]

In [81]:
# Se realiza una función lambda que quite los "-" al IdSucursal ya que dificulta la esteticidad 
# para las posteriores consultas tambien en las bases de datos.
semana1304['IdSucursal']=semana1304['IdSucursal'].astype(str).apply(lambda x: x.replace('-',''))

In [82]:
semana1304.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472166 entries, 0 to 472165
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   Precio      472153 non-null  float64
 1   IdProducto  472151 non-null  object 
 2   IdSucursal  472166 non-null  object 
dtypes: float64(1), object(2)
memory usage: 10.8+ MB


In [83]:
# Agregar "0" a la izquierda hasta completar los caracteres fijos de 8 para IdSucursal.
semana1304["IdSucursal"]= semana1304["IdSucursal"].str.zfill(8)

In [85]:
semana1304.drop_duplicates()

Precio     IdProducto IdSucursal
0        29.90  0000000001663   00021014
1        29.90  0000000002288   00021032
2        39.90  0000000002288   00021096
3       499.99  0000000205870   00091686
4       519.99  0000000205870   00092248
...        ...            ...        ...
472161  139.99  9569753142128   00002511
472162   34.99  9795403001143   00002511
472163  312.50  9990385651922   00000513
472164  312.50  9990385651939   00000513
472165  198.90  9990385651946   00000513

[472134 rows x 3 columns]

In [86]:
semana1304=semana1304.reindex(columns=["IdProducto","IdSucursal","Precio"])

In [87]:
semana1304.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472166 entries, 0 to 472165
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   IdProducto  472151 non-null  object 
 1   IdSucursal  472166 non-null  object 
 2   Precio      472153 non-null  float64
dtypes: float64(1), object(2)
memory usage: 10.8+ MB


In [88]:
# Reemplazar los nulos de "IdProducto" y "Precio" por "0". Como criterio al menos en este caso no lo eliminaría por que son pocos y 
# es tal vez un dato recuperable y a su vez la columna de IdProducto es importante. Luego se consultaría con Data Analyst 
# o ejecutivos sobre la decisión a tomar al respecto. Ya que no es objeto de estudio en este caso. En el precio como posible 
# sugerencia para consultar en el caso de que no existan datos y no se puedan recuperar, un criterio podría ser el promedio de 
# las distintas sucursarles.

semana1304["IdProducto"]=semana1304["IdProducto"].fillna(0)
semana1304["Precio"]=semana1304["Precio"].fillna(0)

In [90]:
semana1304.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472166 entries, 0 to 472165
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype  
---  ------      --------------   -----  
 0   IdProducto  472166 non-null  object 
 1   IdSucursal  472166 non-null  object 
 2   Precio      472166 non-null  float64
dtypes: float64(1), object(2)
memory usage: 10.8+ MB


In [89]:
semana1304

IdProducto IdSucursal  Precio
0       0000000001663   00021014   29.90
1       0000000002288   00021032   29.90
2       0000000002288   00021096   39.90
3       0000000205870   00091686  499.99
4       0000000205870   00092248  519.99
...               ...        ...     ...
472161  9569753142128   00002511  139.99
472162  9795403001143   00002511   34.99
472163  9990385651922   00000513  312.50
472164  9990385651939   00000513  312.50
472165  9990385651946   00000513  198.90

[472166 rows x 3 columns]

In [91]:
# Ver si exportar sin indice o si puede llegar a ser util para algo el dia de mañana.
semana1304.to_csv("Semana1304.csv",index=False)


In [189]:
# Cargar archivo csv.
sucursal = pd.read_csv("sucursal.csv")
sucursal


IdSucursal      DescripcionBandera                  RazonSocial  \
0            117              Super Mami              Dinosaurio S.A.   
1           1011  Hipermercado Carrefour                     INC S.A.   
2          10110  Hipermercado Carrefour                     INC S.A.   
3          10111  Hipermercado Carrefour                     INC S.A.   
4         101112  Hipermercado Carrefour                     INC S.A.   
...          ...                     ...                          ...   
2328      935277                   Jumbo  Jumbo Retail Argentina S.A.   
2329      935626                   Jumbo  Jumbo Retail Argentina S.A.   
2330      935961                   Jumbo  Jumbo Retail Argentina S.A.   
2331       93628                   Jumbo  Jumbo Retail Argentina S.A.   
2332       93662                   Jumbo  Jumbo Retail Argentina S.A.   

                                        Direccion  \
0                                   E53 1011 None   
1                       Bernardo De Irigoyen 2647   
2                                Av. Vergara 1910   
3                           Av. Arturo Illia 3770   
4                                20 De Febrero 37   
...                                           ...   
2328                          Yrigoyen Hipolito 0   
2329                        Boulogne Sur Mer 1275   
2330                        Avenida Santa Fe 4950   
2331  Avenida Del Libertador Gral San Martin 2271   
2332                         Acceso Pilar Norte 0   

                         Localidad Provincia    Latitud   Longitud  IdBandera  \
0                      Salsipuedes      AR-X -31.126667 -64.295250          1   
1                       San Isidro      AR-B -34.491345 -58.589025          1   
2                       Hurlingham      AR-B -34.620610 -58.633769          1   
3              Malvinas Argentinas      AR-B -34.528883 -58.701631          1   
4                            Salta      AR-A -24.789072 -65.413699          1   
...                            ...       ...        ...        ...        ...   
2328            Comodoro Rivadavia      AR-U -45.873300 -67.493500          3   
2329               General Pacheco      AR-B -34.474500 -58.625700          3   
2330  Ciudad Autonoma Buenos Aires      AR-C -34.577200 -58.430000          3   
2331                  San Fernando      AR-B -34.446900 -58.545700          3   
2332                      Del Viso      AR-B -34.436000 -58.808000          3   

      IdComercio  
0              1  
1             10  
2             10  
3             10  
4             10  
...          ...  
2328           9  
2329           9  
2330           9  
2331           9  
2332           9  

[2333 rows x 10 columns]

In [197]:
sucursal = sucursal.set_index('IdSucursal')

In [210]:
sucursal.columns.get_loc("Jumbo")

KeyError: 'Jumbo'

In [206]:
sucursal.loc[sucursal["IdSucursal"]==93662]

KeyError: 'IdSucursal'

In [142]:
# Ver información del DataFrame. No tienen datos nulos. Se chequean los tipos de datos.
sucursal.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2333 entries, 0 to 2332
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   id                   2333 non-null   object 
 1   comercioId           2333 non-null   int64  
 2   banderaId            2333 non-null   int64  
 3   banderaDescripcion   2333 non-null   object 
 4   comercioRazonSocial  2333 non-null   object 
 5   provincia            2333 non-null   object 
 6   localidad            2333 non-null   object 
 7   direccion            2333 non-null   object 
 8   lat                  2333 non-null   float64
 9   lng                  2333 non-null   float64
 10  sucursalNombre       2333 non-null   object 
 11  sucursalTipo         2333 non-null   object 
dtypes: float64(2), int64(2), object(8)
memory usage: 218.8+ KB


In [143]:
# Renombrar las columnas. Criterio utilizado: "PascalCase".
sucursal = sucursal.rename(columns={"id": "IdSucursal", "comercioId": "IdComercio", "banderaId": "IdBandera", "banderaDescripcion": "DescripcionBandera",
                                    "comercioRazonSocial": "RazonSocial", "provincia": "Provincia", "localidad": "Localidad", "direccion": "Direccion",
                                    "lat": "Latitud", "lng": "Longitud", "sucursalNombre": "NombreSucursal", "sucursalTipo": "TipoSucursal"})
sucursal


IdSucursal  IdComercio  IdBandera      DescripcionBandera  \
0         1-1-7           1          1              Super MAMI   
1        10-1-1          10          1  Hipermercado Carrefour   
2       10-1-10          10          1  Hipermercado Carrefour   
3       10-1-11          10          1  Hipermercado Carrefour   
4      10-1-112          10          1  Hipermercado Carrefour   
...         ...         ...        ...                     ...   
2328   9-3-5277           9          3                   Jumbo   
2329   9-3-5626           9          3                   Jumbo   
2330   9-3-5961           9          3                   Jumbo   
2331    9-3-628           9          3                   Jumbo   
2332    9-3-662           9          3                   Jumbo   

                      RazonSocial Provincia                     Localidad  \
0                 Dinosaurio S.A.      AR-X                   SALSIPUEDES   
1                        INC S.A.      AR-B                    San Isidro   
2                        INC S.A.      AR-B                    Hurlingham   
3                        INC S.A.      AR-B           Malvinas Argentinas   
4                        INC S.A.      AR-A                         Salta   
...                           ...       ...                           ...   
2328  Jumbo Retail Argentina S.A.      AR-U            COMODORO RIVADAVIA   
2329  Jumbo Retail Argentina S.A.      AR-B               GENERAL PACHECO   
2330  Jumbo Retail Argentina S.A.      AR-C  CIUDAD AUTONOMA BUENOS AIRES   
2331  Jumbo Retail Argentina S.A.      AR-B                  SAN FERNANDO   
2332  Jumbo Retail Argentina S.A.      AR-B                      DEL VISO   

                                        Direccion    Latitud   Longitud  \
0                                   E53 1011 None -31.126667 -64.295250   
1                       Bernardo De Irigoyen 2647 -34.491345 -58.589025   
2                                Av. Vergara 1910 -34.620610 -58.633769   
3                           Av. Arturo Illia 3770 -34.528883 -58.701631   
4                                20 De Febrero 37 -24.789072 -65.413699   
...                                           ...        ...        ...   
2328                          Yrigoyen Hipolito 0 -45.873300 -67.493500   
2329                        Boulogne Sur Mer 1275 -34.474500 -58.625700   
2330                        Avenida Santa Fe 4950 -34.577200 -58.430000   
2331  Avenida Del Libertador Gral San Martin 2271 -34.446900 -58.545700   
2332                         Acceso Pilar Norte 0 -34.436000 -58.808000   

             NombreSucursal  TipoSucursal  
0              Super Mami 4  Hipermercado  
1                San Isidro  Hipermercado  
2               Villa Tesei  Hipermercado  
3       Malvinas Argentinas  Hipermercado  
4                     Salta  Hipermercado  
...                     ...           ...  
2328         Jumbo-Comodoro  Hipermercado  
2329     Jumbo Pacheco Novo  Hipermercado  
2330     Jumbo Av. Santa Fé  Supermercado  
2331     Jumbo San Fernando  Supermercado  
2332  Jumbo Paseo del Pilar  Supermercado  

[2333 rows x 12 columns]

In [144]:
# Unificar en la columna "Marca" las primeras letras en mayúsculas de cada palabra. A la columna Provincia la dejamos asi 
# porque no tenemos suficiente información para saber a cual provincia pertenece cada una y no es significativo para nuestro análisis.
# Se lo dejamos como consulta al Data Analyst o quien corresponda sobre si a futuro pretenden realizar algún cambio de criterio. 
sucursal["DescripcionBandera"]=sucursal["DescripcionBandera"].str.title()
sucursal["Localidad"]=sucursal["Localidad"].str.title()
sucursal["NombreSucursal"]=sucursal["NombreSucursal"].str.title()

In [145]:
sucursal

IdSucursal  IdComercio  IdBandera      DescripcionBandera  \
0         1-1-7           1          1              Super Mami   
1        10-1-1          10          1  Hipermercado Carrefour   
2       10-1-10          10          1  Hipermercado Carrefour   
3       10-1-11          10          1  Hipermercado Carrefour   
4      10-1-112          10          1  Hipermercado Carrefour   
...         ...         ...        ...                     ...   
2328   9-3-5277           9          3                   Jumbo   
2329   9-3-5626           9          3                   Jumbo   
2330   9-3-5961           9          3                   Jumbo   
2331    9-3-628           9          3                   Jumbo   
2332    9-3-662           9          3                   Jumbo   

                      RazonSocial Provincia                     Localidad  \
0                 Dinosaurio S.A.      AR-X                   Salsipuedes   
1                        INC S.A.      AR-B                    San Isidro   
2                        INC S.A.      AR-B                    Hurlingham   
3                        INC S.A.      AR-B           Malvinas Argentinas   
4                        INC S.A.      AR-A                         Salta   
...                           ...       ...                           ...   
2328  Jumbo Retail Argentina S.A.      AR-U            Comodoro Rivadavia   
2329  Jumbo Retail Argentina S.A.      AR-B               General Pacheco   
2330  Jumbo Retail Argentina S.A.      AR-C  Ciudad Autonoma Buenos Aires   
2331  Jumbo Retail Argentina S.A.      AR-B                  San Fernando   
2332  Jumbo Retail Argentina S.A.      AR-B                      Del Viso   

                                        Direccion    Latitud   Longitud  \
0                                   E53 1011 None -31.126667 -64.295250   
1                       Bernardo De Irigoyen 2647 -34.491345 -58.589025   
2                                Av. Vergara 1910 -34.620610 -58.633769   
3                           Av. Arturo Illia 3770 -34.528883 -58.701631   
4                                20 De Febrero 37 -24.789072 -65.413699   
...                                           ...        ...        ...   
2328                          Yrigoyen Hipolito 0 -45.873300 -67.493500   
2329                        Boulogne Sur Mer 1275 -34.474500 -58.625700   
2330                        Avenida Santa Fe 4950 -34.577200 -58.430000   
2331  Avenida Del Libertador Gral San Martin 2271 -34.446900 -58.545700   
2332                         Acceso Pilar Norte 0 -34.436000 -58.808000   

             NombreSucursal  TipoSucursal  
0              Super Mami 4  Hipermercado  
1                San Isidro  Hipermercado  
2               Villa Tesei  Hipermercado  
3       Malvinas Argentinas  Hipermercado  
4                     Salta  Hipermercado  
...                     ...           ...  
2328         Jumbo-Comodoro  Hipermercado  
2329     Jumbo Pacheco Novo  Hipermercado  
2330     Jumbo Av. Santa Fé  Supermercado  
2331     Jumbo San Fernando  Supermercado  
2332  Jumbo Paseo Del Pilar  Supermercado  

[2333 rows x 12 columns]

In [146]:
# Se realiza una función lambda que quite los "-" al IdSucursal ya que dificulta la esteticidad 
# para las posteriores consultas tambien en las bases de datos.

sucursal['IdSucursal']=sucursal['IdSucursal'].apply(lambda x: x.replace('-',''))

In [147]:
sucursal["IdSucursal"].max()

'93662'

In [148]:
# Se agregan ceros a la izquierda para completar los caracteres en la columna IdSucursal de 8 dígitos
sucursal["IdSucursal"]=sucursal["IdSucursal"].str.zfill(8)

In [149]:
sucursal.drop_duplicates()

IdSucursal  IdComercio  IdBandera      DescripcionBandera  \
0      00000117           1          1              Super Mami   
1      00001011          10          1  Hipermercado Carrefour   
2      00010110          10          1  Hipermercado Carrefour   
3      00010111          10          1  Hipermercado Carrefour   
4      00101112          10          1  Hipermercado Carrefour   
...         ...         ...        ...                     ...   
2328   00935277           9          3                   Jumbo   
2329   00935626           9          3                   Jumbo   
2330   00935961           9          3                   Jumbo   
2331   00093628           9          3                   Jumbo   
2332   00093662           9          3                   Jumbo   

                      RazonSocial Provincia                     Localidad  \
0                 Dinosaurio S.A.      AR-X                   Salsipuedes   
1                        INC S.A.      AR-B                    San Isidro   
2                        INC S.A.      AR-B                    Hurlingham   
3                        INC S.A.      AR-B           Malvinas Argentinas   
4                        INC S.A.      AR-A                         Salta   
...                           ...       ...                           ...   
2328  Jumbo Retail Argentina S.A.      AR-U            Comodoro Rivadavia   
2329  Jumbo Retail Argentina S.A.      AR-B               General Pacheco   
2330  Jumbo Retail Argentina S.A.      AR-C  Ciudad Autonoma Buenos Aires   
2331  Jumbo Retail Argentina S.A.      AR-B                  San Fernando   
2332  Jumbo Retail Argentina S.A.      AR-B                      Del Viso   

                                        Direccion    Latitud   Longitud  \
0                                   E53 1011 None -31.126667 -64.295250   
1                       Bernardo De Irigoyen 2647 -34.491345 -58.589025   
2                                Av. Vergara 1910 -34.620610 -58.633769   
3                           Av. Arturo Illia 3770 -34.528883 -58.701631   
4                                20 De Febrero 37 -24.789072 -65.413699   
...                                           ...        ...        ...   
2328                          Yrigoyen Hipolito 0 -45.873300 -67.493500   
2329                        Boulogne Sur Mer 1275 -34.474500 -58.625700   
2330                        Avenida Santa Fe 4950 -34.577200 -58.430000   
2331  Avenida Del Libertador Gral San Martin 2271 -34.446900 -58.545700   
2332                         Acceso Pilar Norte 0 -34.436000 -58.808000   

             NombreSucursal  TipoSucursal  
0              Super Mami 4  Hipermercado  
1                San Isidro  Hipermercado  
2               Villa Tesei  Hipermercado  
3       Malvinas Argentinas  Hipermercado  
4                     Salta  Hipermercado  
...                     ...           ...  
2328         Jumbo-Comodoro  Hipermercado  
2329     Jumbo Pacheco Novo  Hipermercado  
2330     Jumbo Av. Santa Fé  Supermercado  
2331     Jumbo San Fernando  Supermercado  
2332  Jumbo Paseo Del Pilar  Supermercado  

[2333 rows x 12 columns]

In [152]:
# Este criterio de asignacion se decide por "importancia", primero "IdSucursal", ya que es el código único y futura PK, luego 
# "DescripcionBandera" que es el nombre de la cadena de la empresa, luego "RazonSocial" que es el nombre del grupo, posteriormente
# la dirección desde lo más específico a lo más general ("Dirección","Localidad","Provincia","Latitud" y "Longitud") y por último 
# los restantes "Id"("Bandera" y "Comercio"), componentes del "IdSucursal" identificando a la bandera y comercio respectivamente.

sucursal=sucursal.reindex(columns=["IdSucursal","DescripcionBandera","RazonSocial","Direccion","Localidad",
                            "Provincia","Latitud","Longitud","IdBandera","IdComercio"])

In [155]:
sucursal

IdSucursal      DescripcionBandera                  RazonSocial  \
0      00000117              Super Mami              Dinosaurio S.A.   
1      00001011  Hipermercado Carrefour                     INC S.A.   
2      00010110  Hipermercado Carrefour                     INC S.A.   
3      00010111  Hipermercado Carrefour                     INC S.A.   
4      00101112  Hipermercado Carrefour                     INC S.A.   
...         ...                     ...                          ...   
2328   00935277                   Jumbo  Jumbo Retail Argentina S.A.   
2329   00935626                   Jumbo  Jumbo Retail Argentina S.A.   
2330   00935961                   Jumbo  Jumbo Retail Argentina S.A.   
2331   00093628                   Jumbo  Jumbo Retail Argentina S.A.   
2332   00093662                   Jumbo  Jumbo Retail Argentina S.A.   

                                        Direccion  \
0                                   E53 1011 None   
1                       Bernardo De Irigoyen 2647   
2                                Av. Vergara 1910   
3                           Av. Arturo Illia 3770   
4                                20 De Febrero 37   
...                                           ...   
2328                          Yrigoyen Hipolito 0   
2329                        Boulogne Sur Mer 1275   
2330                        Avenida Santa Fe 4950   
2331  Avenida Del Libertador Gral San Martin 2271   
2332                         Acceso Pilar Norte 0   

                         Localidad Provincia    Latitud   Longitud  IdBandera  \
0                      Salsipuedes      AR-X -31.126667 -64.295250          1   
1                       San Isidro      AR-B -34.491345 -58.589025          1   
2                       Hurlingham      AR-B -34.620610 -58.633769          1   
3              Malvinas Argentinas      AR-B -34.528883 -58.701631          1   
4                            Salta      AR-A -24.789072 -65.413699          1   
...                            ...       ...        ...        ...        ...   
2328            Comodoro Rivadavia      AR-U -45.873300 -67.493500          3   
2329               General Pacheco      AR-B -34.474500 -58.625700          3   
2330  Ciudad Autonoma Buenos Aires      AR-C -34.577200 -58.430000          3   
2331                  San Fernando      AR-B -34.446900 -58.545700          3   
2332                      Del Viso      AR-B -34.436000 -58.808000          3   

      IdComercio  
0              1  
1             10  
2             10  
3             10  
4             10  
...          ...  
2328           9  
2329           9  
2330           9  
2331           9  
2332           9  

[2333 rows x 10 columns]

In [154]:
sucursal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2333 entries, 0 to 2332
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   IdSucursal          2333 non-null   object 
 1   DescripcionBandera  2333 non-null   object 
 2   RazonSocial         2333 non-null   object 
 3   Direccion           2333 non-null   object 
 4   Localidad           2333 non-null   object 
 5   Provincia           2333 non-null   object 
 6   Latitud             2333 non-null   float64
 7   Longitud            2333 non-null   float64
 8   IdBandera           2333 non-null   int64  
 9   IdComercio          2333 non-null   int64  
dtypes: float64(2), int64(2), object(6)
memory usage: 182.4+ KB


In [156]:
# Exportar a carpeta local.
sucursal.to_csv("Sucursal.csv",index=False)


In [157]:
# Exportar a carpeta de MySQL.
sucursal.to_csv(r"C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\Sucursal.csv",index=False)
